export const ADD_STUDENT_TO_GROUP = 'ADD_STUDENT_TO_GROUP';
export const DELETE_STUDENT_FROM_GROUP = 'DELETE_STUDENT_FROM_GROUP';
export const RECEIVE_STUDENT_LIST = 'RECEIVE_STUDENT_LIST';
export const ERROR_STUDENT_LIST = 'ERROR_STUDENT_LIST';
export const RECEIVE_POSTGROUP = 'RECEIVE_POSTGROUP';
export const RECEIVE_GROUPS_LIST = 'RECEIVE_GROUPS_LIST';
export const ERROR_GROUPS_LIST = 'ERROR_GROUPS_LIST';
