export const ADD_STUDENT_TO_GROUP = 'ADD_STUDENT_TO_GROUP';
export const DELETE_STUDENT_FROM_GROUP = 'DELETE_STUDENT_FROM_GROUP';
export const RECEIVE_STUDENTLIST = 'RECEIVE_STUDENTLIST';
export const ERROR_STUDENTLIST = 'ERROR_STUDENTLIST';
