export const RECEIVE_TOPICS_MATERIALS = 'RECEIVE_TOPICS_MATERIALS';
export const ERROR_TOPICS_MATERIALS = 'ERROR_TOPICS_MATERIALS';
export const RECEIVE_MATERIALS = 'RECEIVE_MATERIALS';
export const ERROR_MATERIALS = 'ERROR_MATERIALS';
