export const ADD_STUDENT = 'ADD_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const RECEIVE_TESTS_ASSIGNED_TO_USER = 'RECEIVE_TESTS_ASSIGNED_TO_USER';
export const ERROR_STUDENTS_BY_GROUP = 'ERROR_STUDENTS_BY_GROUP';
