export const ADD_GROUP = 'ADD_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const RECEIVE_ALL_GROUPS_LIST = 'RECEIVE_ALL_GROUPS_LIST';
export const ERROR_ALL_GROUPS_LIST = 'ERROR_ALL_GROUPS_LIST';
