export const ADD_QUESTION_TAG = 'ADD_QUESTION_TAG';
export const DELETE_QUESTION_TAG = 'DELETE_QUESTION_TAG';
export const RECEIVE_ADD_QUESTIONS = 'RECEIVE_ADD_QUESTIONS';
export const ERROR_ADD_QUESTIONS = 'ERROR_ADD_QUESTIONS';
export const RECEIVE_TOPICS_ADD_QUESTION = 'RECEIVE_TOPICS_ADD_QUESTION';
export const ERROR_TOPICS_ADD_QUESTION = 'ERROR_TOPICS_ADD_QUESTION';
