package com.exadel.team3.backend.dto;

public enum ActivityType {
    USER_REGISTERED,
    TRAINING_TEST_STARTED,
    TRAINING_TEST_SUBMITTED,
    CONTROL_TEST_ASSIGNED,
    CONTROL_TEST_CHECK_NEEDED,
    CONTROL_TEST_SUBMITTED,
    TASK_ASSIGNED,
    TASK_FINISHED
}
