export const ADD_STUDENT = 'ADD_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const RECEIVE_STUDENTS_BY_GROUP = 'RECEIVE_STUDENTS_BY_GROUP';
export const ERROR_STUDENTS_BY_GROUP = 'ERROR_STUDENTS_BY_GROUP';
