export const ADD_STUDENT = 'ADD_STUDENT';
export const RECEIVE_DELETE_STUDENT = 'RECEIVE_DELETE_STUDENT';
export const RECEIVE_STUDENTS_BY_GROUP = 'RECEIVE_STUDENTS_BY_GROUP';
export const ERROR_STUDENTS_BY_GROUP = 'ERROR_STUDENTS_BY_GROUP';
export const GET_NAME_GROUP = 'GET_NAME_GROUP';
export const RECEIVE_ASSIGNED_TASKS = 'RECEIVE_ASSIGNED_TASKS';
export const RECEIVE_TASKS_INFO_FOR_GROUP = 'RECEIVE_ASSIGNED_TASKS';
