export const RECEIVE_TASK = 'RECEIVE_TASK';
export const CREATE_TASK = 'CREATE_TEST';
export const RECEIVE_ALL_TASKS_ASSIGN = 'RECEIVE_ALL_TASKS_ASSIGN';
export const ERROR_ALL_TASKS_ASSIGN = 'ERROR_ALL_TASKS_ASSIGN';
