export const ADD_TASK_TAG = 'ADD_TASK_TAG';
export const DELETE_TASK_TAG = 'DELETE_TASK_TAG';
export const DELETE_STUDENT_FROM_LIST_TASK = 'DELETE_STUDENT_FROM_LIST_TASK';
export const ADD_STUDENT_TO_LIST_TASK = 'ADD_STUDENT_TO_LIST_TASK';
export const RECEIVE_STUDENTS_LIST_FOR_TASK = 'RECEIVE_STUDENTS_LIST_FOR_TASK';
export const ERROR_STUDENTS_LIST_FOR_TASK = 'ERROR_STUDENTS_LIST_FOR_TASK';
export const RECEIVE_GROUPS_LIST_FOR_TASK = 'RECEIVE_GROUPS_LIST_FOR_TEST';
export const ERROR_GROUPS_LIST_FOR_TASK = 'ERROR_GROUPS_LIST_FOR_TASK';
