export const ADD_IN_OUT_SET = 'ADD_IN_OUT_SET';
export const ADD_TASK_TAG = 'ADD_TASK_TAG';
export const DELETE_TASK_TAG = 'DELETE_TASK_TAG';
export const RECEIVE_TOPICS_ADD_TASK = 'RECEIVE_TOPICS_ADD_TASK';
export const ERROR_TOPICS_ADD_TASK = 'ERROR_TOPICS_ADD_TASK';
export const ERROR_ADD_TASK = 'ERROR_TOPICS_ADD_TASK';
export const RECIEVE_ADD_TASK = 'ERROR_TOPICS_ADD_TASK';
