export const ERROR_POST_UPLOAD_FILES = 'ERROR_GROUPS_LIST_FOR_TEST';
export const RECEIVE_POST_UPLOAD_FILES = 'RECEIVE_POST_UPLOAD_FILES';
export const RECEIVE_USER_TASK_INFORMATION = 'RECEIVE_USER_TASK_INFORMATION';
export const ERROR_USER_TASK_INFORMATION = 'ERROR_USER_TASK_INFORMATION';
