export const RECEIVE_REGISTRATED_STUDENT = 'RECEIVE_REGISTRATED_STUDENT';
export const RECEIVE_REGISTRATED_TEACHER = 'RECEIVE_REGISTRATED_TEACHER';
export const EDIT_TEACHER = 'EDIT_TEACHER';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const ERROR_REGISTRATED_STUDENT = 'ERROR_REGISTRATED_STUDENT';
export const ERROR_REGISTRATED_TEACHER = 'ERROR_REGISTRATED_TEACHER';
