export const CREATE_TEST = 'CREATE_TEST';
export const ADD_TEST_TAG = 'ADD_TEST_TAG';
export const DELETE_TEST_TAG = 'DELETE_TEST_TAG';
export const DELETE_STUDENT_FROM_LIST = 'DELETE_STUDENT_FROM_LIST';
export const ADD_STUDENT_TO_LIST = 'ADD_STUDENT_TO_LIST';
export const RECEIVE_STUDENTLIST_FOR_TEST = 'RECEIVE_STUDENTLIST_FOR_TEST';
export const ERROR_STUDENTLIST_FOR_TEST = 'ERROR_STUDENTLIST_FOR_TEST';
