export const RECEIVE_EDIT_USER = 'RECEIVE_EDIT_USER';
export const ERROR_EDIT_USER = 'ERROR_EDIT_USER';
export const RECEIVE_GET_USER_FOR_PROFILE = 'RECEIVE_GET_USER_FOR_PROFILE';
export const RECEIVE_CHANGE_PASSWORD = 'RECEIVE_CHANGE_PASSWORD';
export const ERROR_CHANGE_PASSWORD = 'ERROR_CHANGE_PASSWORD';
