export const RECEIVE_TRAINING_TEST = 'RECEIVE_TRAINING_TEST';
export const ERROR_TRAINING_TEST = 'ERROR_TRAINING_TEST';
export const ADD_TRAINING_TOPIC = 'ADD_TRAINING_TOPIC';
export const RECEIVE_TOPICS_TRAINING_TEST = 'RECEIVE_TOPICS_TRAINING_TEST';
