export const ADD_STUDENT_TOP_BY_SUM = 'ADD_STUDENT_TOP_BY_SUM';
export const ADD_STUDENT_TOP_BY_ACTIVITY = 'ADD_STUDENT_TOP_BY_ACTIVITY';
export const ADD_STUDENT_TOP_BY_TASK = 'ADD_STUDENT_TOP_BY_TASK';
