export const RECEIVE_STUDENT_TOP_BY_SUM = 'RECEIVE_STUDENT_TOP_BY_SUM';
export const RECEIVE_STUDENT_TOP_BY_ACTIVITY = 'RECEIVE_STUDENT_TOP_BY_ACTIVITY';
export const RECEIVE_STUDENT_TOP_BY_TASK = 'RECEIVE_STUDENT_TOP_BY_TASK';
